#!/bin/sh
#
#  Copyright (c) 2012 Samuel Lidén Borell <samuel@kodafritt.se>
#
#  Permission is hereby granted, free of charge, to any person obtaining a copy
#  of this software and associated documentation files (the "Software"), to deal
#  in the Software without restriction, including without limitation the rights
#  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
#  copies of the Software, and to permit persons to whom the Software is
#  furnished to do so, subject to the following conditions:
#  
#  The above copyright notice and this permission notice shall be included in
#  all copies or substantial portions of the Software.
#  
#  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
#  THE SOFTWARE.
#

if [ $# = 0 ]; then
    echo "Usage: dirwine ARGUMENTS..."
    echo
    echo "Runs Wine in the Windows installation that the current directory belongs "
    echo "to. This is done by setting WINEPREFIX set to the first parent directory "
    echo "containing a wine installation (with system.reg, user.reg and dosdevices/)."
    echo "The arguments are passed as-is to wine."
    echo
    exit 2
fi


findwineprefix() {
    (
        while true; do
            if [ -e system.reg -a -e user.reg -a -d dosdevices ]; then
                # Found a Wine dir
                echo "$PWD"
                return 0
            fi
            
            LASTDIR="$PWD"
            cd .. || return 1
            if [ "$LASTDIR" = "$PWD" ]; then
                return 1
            fi
        done
    )
}

WINEPREFIX=`findwineprefix`

if [ -z "$WINEPREFIX" ]; then
    echo "Couldn't find a wine prefix here." >&2
    exit 1
fi

#echo $WINEPREFIX
export WINEPREFIX
wine $@

